### ISSUE TITLE
transaction_id can be just an integer but dinermail accepts also any string

### ISSUE THREAD

**Issue by ghost** [nicolas-simplex/dineromail#1]
Hi,

Could you put a note that the generated transaction_id must be an integer or change it to be a string since dineromail accepts strings of any kind.

Thanks!

tag 'operacion'
element :transaction_id, String, :tag => 'id'
element :type, String, :tag => 'tipo'

**Comment by nicolas-simplex** [comment]
This issue is fixed in version 0.2.0. 
Please let me know if it is working well.

**Comment by ghost** [comment]
ok, thanks! Will check later and I'll let you know.
